### ISSUE TITLE
Нужна помощь с 53-ей страницей записок

### ISSUE THREAD

**Issue by stalker57241** [devsienko/c4os#1]
1) На 53 странице вы указали в коде на Си kernel_main, хотя startup.asm работает именно с _kernel_main, из-за чего ld не хочет компилировать этот вариант.
2) в startup.asm нужно переписать регистры в 64-битные, как и архитектуру ELF в ELF64 (Или как скомпилировать файл Си на gcc в 32-битную архитектуру, здесь всё из коробки работает, судя по `запискам`).

Sorry for russian.

**Comment by devsienko** [comment]
Привет, а ты на винде это пытаешься сделать? По поводу регистров у меня не было необходимости 64 битные использвать, как в 32 архитектуру скомпилировать сходу не отвечу, надо освежить память. Если хочешь можешь в tg написать d_evsienko.

**Comment by devsienko** [comment]
И да, все работает из коробки, но я кроме как на своем енвайронменте не тестировал, я упоминал что на 10 винде все делал.

**Comment by stalker57241** [comment]
> Привет, а ты на винде это пытаешься сделать? По поводу регистров у меня не было необходимости 64 битные использвать, как в 32 архитектуру скомпилировать сходу не отвечу, надо освежить память. Если хочешь можешь в tg написать d_evsienko.

Да винда 10-ая, 64-битный процессор. Почему-то, либо си файл компилируется в 64-битную архитектуру, либо asm в 32-битную. Я смог это запустить, подставив use32 в начале, но "Hello, world!" появляться отказывается. Похоже, мне нужно, либо соорудить эмулятор 32-битной архитектуры, либо поставить 32-битный gcc.

**Comment by stalker57241** [comment]
Я добавил в вызов gcc аргумент -m32 для компиляции в 32-битную архитектуру, затем в ld добавил -m i386pe для того, что выходной файл был в нужной архитектуре и совпадал со входом. На этом ld начал жаловаться так:
```
bin\startup.o: In function `start':
(.text+0x7): undefined reference to `kernel_main'
```
а вот так выглядит после моих бесчеловечно тяжёлых экспериментов startup.asm
```
format ELF

public _start
extrn kernel_main
section ".text" executable

_start:
        movzx edx, dl
        push edx
        push esi
        push ebx
        call kernel_main
 @@:
        jmp @b

; section ".data" writable
```

**Comment by stalker57241** [comment]
В итоге я нашёл всё, что нужно. Сначала попал на китайский форум, где ориентировался по английским словам, когда они вообще nasm обсуждали, потом вышел на stackoverflow, где наконец нашёл последние элементы кода. Для других соискателей приключений делюсь своими файлами к выводу "hello, world!"
[src_files.zip](https://github.com/devsienko/c4os/files/9538296/src_files.zip)
[kernel_build.zip](https://github.com/devsienko/c4os/files/9538298/kernel_build.zip)

**Comment by devsienko** [comment]
гуд) еще если будут какие то сомнения советую смотреть на финальное состояние исходников, потому что бывало, что в промежуточных коммитах баги, которые в последующих были пофикшены.
